# Generated by Django 3.2.3 on 2021-06-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('p_no', models.PositiveBigIntegerField()),
                ('aadhar_no', models.PositiveBigIntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
