# Generated by Django 3.2.3 on 2021-06-07 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20210607_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='pro_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='./dataset'),
            preserve_default=False,
        ),
    ]
