# Generated by Django 3.2.3 on 2021-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_register_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
