# Generated by Django 3.2.3 on 2021-06-07 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_register_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pro_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dataset'),
            preserve_default=False,
        ),
    ]
