# Generated by Django 3.2.3 on 2021-06-08 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_register_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 6, 8, 10, 22, 55, 666779, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attendance', models.BooleanField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='signup.register', verbose_name='username')),
            ],
        ),
    ]
