# Generated by Django 3.2.3 on 2021-06-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20210608_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
    ]
