# Generated by Django 3.2.3 on 2021-06-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_remove_profile_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
