# Generated by Django 3.2.3 on 2021-06-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_remove_profile_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
