# Generated by Django 3.2.3 on 2021-06-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
