# Generated by Django 3.2.3 on 2021-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0012_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('p_no', models.PositiveBigIntegerField()),
                ('aadhar_no', models.PositiveBigIntegerField()),
                ('profession', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
                ('pro_pic', models.ImageField(upload_to='dataset')),
            ],
        ),
    ]
