# Generated by Django 3.2.3 on 2021-06-08 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_auto_20210608_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
    ]
