# Generated by Django 3.2.3 on 2021-06-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0018_auto_20210609_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
    ]
