# Generated by Django 3.2.3 on 2021-06-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0021_alter_register_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
    ]
