# Generated by Django 3.2.3 on 2021-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0025_auto_20210609_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
