# Generated by Django 3.2.3 on 2021-06-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0027_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
