# Generated by Django 3.2.3 on 2021-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0028_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='abnormal',
            field=models.BooleanField(default=False),
        ),
    ]
