# Generated by Django 3.2.3 on 2021-06-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0030_auto_20210611_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='abnormal',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='attendance',
            field=models.BooleanField(default='True'),
        ),
    ]
