# Generated by Django 3.2.3 on 2021-06-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0031_auto_20210615_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attendance', models.BooleanField(default='True')),
                ('abnormal', models.BooleanField(default='False')),
            ],
        ),
    ]
